---

- name: Creating Directory for Storm.
  file: path={{ storm_local_dir }} owner={{ storm_user }} group={{ storm_group }} state=directory

- name: Creating Directory for Storm.
  file: path={{ storm_log_dir }} owner={{ storm_user }} group={{ storm_group }} state=directory

- name: Starting Supervisor.
  command: sh {{ common['soft_link_base_path'] }}/storm/conf/start_supervisor.sh 
  sudo: yes
  sudo_user: "{{ storm_user }}"
