---

  - name: Create a User `"{{ hadoop_user }}"` for all our Hadoop Modules.
    user: name={{ hadoop_user }} password=$6$rounds=40000$1qjG/hovLZOkcerH$CK4Or3w8rR3KabccowciZZUeD.nIwR/VINUa2uPsmGK/2xnmOt80TjDwbof9rNvnYY6icCkdAR2qrFquirBtT1
 
  - name: Create a .ssh Directory.
    file: path=~/.ssh state=directory owner={{ hadoop_user }} group={{ hadoop_group }} mode=0700
    sudo: yes
    sudo_user: "{{ hadoop_user }}"
 
  - name: Lets copy the template id_rsa to auth_keys location.
    template: src=id_rsa.pub dest=~/.ssh/authorized_keys mode=644
    sudo: yes
    sudo_user: "{{ hadoop_user }}"
 
  - name: Lets copy id_rsa to location .ssh.
    template: src=id_rsa dest=~/.ssh/id_rsa mode=600
    sudo: yes
    sudo_user: "{{ hadoop_user }}"
 
  - name: Lets copy id_rsa.pub to location .ssh.
    template: src=id_rsa.pub dest=~/.ssh/id_rsa.pub mode=644
    sudo: yes
    sudo_user: "{{ hadoop_user }}"
