- hosts: all
  remote_user: root
  roles:
    - commons
    - ssh_known_hosts
    - jdk

- hosts: zookeepernodes
  remote_user: root
  roles:
    - zookeeper_install_tarball


##  Need to check, if kafka is already running then we should not run it.
- hosts: kafkanodes
  remote_user: root
  roles:
    - kafka_install_tarball

 hosts: kafkanodes
 remote_user: root
 roles:
   - http2kafka

- hosts: hadoopcluster
  remote_user: root
  roles:
    - ssh_password_less
    - cdh5_hadoop_commons_tarball

- hosts: namenodes
  remote_user: root
  roles:
    - cdh5_hadoop_namenode_active

- hosts: secondarynamenode
  remote_user: root
  roles:
    - cdh5_hadoop_sec_namenode

- hosts: resourcemanager
  remote_user: root
  roles:
    - cdh5_hadoop_resourcemgr

- hosts: datanodes
  remote_user: root
  roles:
    - cdh5_hadoop_datanode

- hosts: stormcluster
  remote_user: root
  roles:
    - storm_commons_tarball

- hosts: stormnimbusnodes
  remote_user: root
  roles:
    - storm_nimbus

- hosts: stormsupervisornodes
  remote_user: root
  roles:
    - storm_supervisor

- hosts: tomcatwebserver
  remote_user: root
  roles:
    - tomcat_webserver
