#
#-----------------------------
#COMMON INSTALLATIONs
#-----------------------------
#

- hosts: preprod
  remote_user: root
  roles:
    - commons
    - ssh_known_hosts
    - jdk


#
#-----------------------------
# ZOOKEEPER CLUSTER SETUP
#-----------------------------
#

- hosts: zookeepernodes
  remote_user: root
  roles:
    - zookeeper_install_tarball

#
#-----------------------------
# KAFKA CLUSTER SETUP
#-----------------------------
#

- hosts: kafkanodes
  remote_user: root
  roles:
    - kafka_install_tarball

#
#-----------------------------
# HTTP2KAFKA SETUP
#-----------------------------
#

- hosts: kafkanodes
  remote_user: root
  roles:
    - http2kafka

#
#-----------------------------
# STORM CLUSTER SETUP
#-----------------------------
#

- hosts: stormcluster
  remote_user: root
  roles:
    - storm_commons_tarball

- hosts: stormnimbusnodes
  remote_user: root
  roles:
    - storm_nimbus

- hosts: stormsupervisornodes
  remote_user: root
  roles:
    - storm_supervisor

#
#-----------------------------
# HADOOP CLUSTER SETUP
#-----------------------------
#


- hosts: hadoopcluster
  remote_user: root
  roles:
    - ssh_password_less
    - cdh5_hadoop_commons_tarball

- hosts: namenodes
  remote_user: root
  roles:
    - cdh5_hadoop_namenode_active

- hosts: secondarynamenode
  remote_user: root
  roles:
    - cdh5_hadoop_sec_namenode

- hosts: resourcemanager
  remote_user: root
  roles:
    - cdh5_hadoop_resourcemgr

- hosts: datanodes
  remote_user: root
  roles:
    - cdh5_hadoop_datanode

- hosts: tomcatwebserver
  remote_user: root
  roles:
    - tomcat_webserver

#
# Creating a Storm User on Namenode/ This will eventually be a edge node.
#
- hosts: namenodes
  remote_user: root
  roles:
    - post_install_setups


#
#-----------------------------
# ZABBIX AGENT SETUP
#-----------------------------
#

- hosts: preprod
  remote_user: root
  roles:
    - zabbix_agent_install
